### ISSUE TITLE
Unable to load parameters

### ISSUE THREAD

**Issue by bademeister99** [RO-Projects/scara#7]
![grafik](https://user-images.githubusercontent.com/123369589/216313578-a396c98d-1371-458b-aa86-f0068b4dcb6b.png)

Ros is unable to set parameters of a Joint Controller

**Comment by Elektron97** [comment]
Maybe you forgot to add the PID gain in the config file. [Here](https://github.com/RO-Projects/scara/blob/main/scara_robot/config/scara_actuation.yaml) you have to specify the pid gain in the third joint:

```yaml
  # Gazebo Ros Control ----------------------------------------
  gazebo_ros_control/pid_gains:
    joint_1: {p: 100.0, i: 0.01, d: 10.0}
    joint_2: {p: 100.0, i: 0.01, d: 10.0}
    joint_3: {p: 100.0, i: 0.01, d: 10.0}
```

**Comment by bademeister99** [comment]
Thank you, i added the gains as you proposed, but still the same problem

**Comment by Elektron97** [comment]
I found the error: As written [here](https://answers.ros.org/question/360930/error-in-robot-control-gazebo-load_parameters-unable-to-set-parameters-last-param-was-bl_wheel_trans_controllerpidi10-cannot-marshal-none-unless/), this error is caused by a **indentation** error in `yaml` file. As in python, you have to pay attention to the indentation. So in your code, you wrote:

```yaml
  joint3_controller:
  type: position_controllers/JointPositionController
  joint: joint_3
```

instead of:
```yaml
  joint3_controller:
    type: position_controllers/JointPositionController
    joint: joint_3
```

This is because you define your `joint3_controller` "object" with its attributes *type* and *joint*.
